### PR TITLE
Added Alphanumeric Qabbala (AQ)

### PR DESCRIPTION
**Pull request by Alektryon**
Hey Matt, how are you?

I forked your project and added a new cipher that I believe will spark your interest.

The cipher in question is called "Alphanumeric Qabbala" (AQ), and it's basically a continuous alphanumeric sequence from 0 to Z. So after 9 comes A=10, then B=11, etc, until Z=35. As you may notice, it is thus intimately related to base36 notation (0-9, A-Z).

The name of the cipher ("AQ") also explains what it is, since A=10 and Q=26, standing for the ten Arabic numerals 0-9, and the twenty-six English letters A-Z.

It's a virtually unknown cipher in the world of English Gematria, even though it delivers some outstanding results that can't be ignored.

I've written about it on my blog:

"The wonders & magic of Alphanumeric Qabbala":
https://gematriaresearch.blogspot.com/2023/02/the-wonders-magic-of-alphanumeric.html

ALSO:

The project has been deployed on Vercel (like yours), and this is its link:
https://gemcalc.vercel.app/

Please check how it works before considering this merge request.

---------------------------------------------------

Some notable synchronistic matches with AQ:

AQ = 10+26
(10 numerals 0-9 plus 26 letters A-Z)

The phrase "AQ=0123456789+ABCDEFGHIJKLMNOPQRSTUVWXYZ" sums 666

"Emmanuel" = 156" = "Nazarene" = "Lamb of God" = "The Word" = "Gospels" = "Passion"
(The 156th prime is 911)

"Jesus" = 119 = "Y'shua" = "Cross" = "Andrew"
(The cross of St. Andrew is in the shape of an "X")
(Also — remember the Ground Zero Cross?)

"X" = 33
(Jesus crucified at 33 years old, according to tradition)

137 (33rd prime) = "Masonic" = "Aprons" = "Messiah" = "Menorah" = "Lucifer" = "Milton" = "Gnosis" = "Wisdom" = "Prayer" = "English" = "Alphabet"

"And God said: Let there be light, and there was light" (Gen 1:3) = 777

"Vortex Mathematics" = 369
(Vortex Mathematics is based on the numbers 3-6-9)

"Metonic Cycle" = 235
(A Metonic cycle corresponds to 235 lunations)

### CODE REVIEW

**Comment by Alektryon** [comment]
Oh, I just didn't add AQ to the `README.md` file because I didn't know what/where was the source of the images -.-'

Edit:

I added Mormon Scriptures to the texts, even though I did it *after* opening this merge request because I thought that, as it was a later modification, it wouldn't show up in the merge request. Not very experienced in merge requests to be honest 😅

**Review by mattcong — APPROVED** [review]
Hi @Alektryon, thanks for this contribution and thanks also for linking your article. Funnily enough, speaking of synchronicities, I first heard about AQ a couple of months ago and started to read about it more intentionally recently so this PR was opened at a very intriguing time.

As you can probably tell my time to work on the calculator is very limited at the moment but I hope to start picking up more feature development soon. There are a few ideas I've been experimenting with that may be of interest and it would be great to get some feedback as to their usefulness.

**Comment by Alektryon** [comment]
I'm more than willing to help, but unfortunately not with programming skills. I understand a (very) little bit of JavaScript but nothing of TypeScript, and I only managed to add AQ because I asked BlackBox.AI for assistance =P

The first try returned an error and wouldn't work, but later I understood where the problem was, asked again for help, and it worked. I love this software of yours. It's easy to use, the "About" menu is very informative, and it has some very nice details (the hand pointing up, the theme toggle option). Great job! And thanks for accepting the merge request. =)

P.S.: By the way, do you mind if I keep my fork of your calculator active?

**Comment by mattcong** [comment]
@Alektryon no worries - this is more from a user perspective than a programming one. Alongside some standard mathematical operations (viewing whether a number is prime, square, etc), I'm planning to add more sequence detection capabilities including bulk text analysis to view patterns across range of words/values. However I'd also welcome any suggestions for features so open an issue if there's anything you'd like to see (or just write it here).

And that's good to hear! Feel free to keep the fork open and incorporate any further changes.

**Pull request merged**
